version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:11
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 5433:8080
